main: org.xafero.mc.weirdpet.MainPlugin
name: WeirdPet
version: 1.0.0
api-version: 1.18
description: Animals are the best friends!
author: xafero
commands:
  petfind:
    description: Find pets nearby
    usage: /<command> [radius]
